name: Monitor Insolventa

on:
  schedule:
    - cron: '0 6,8,10,12,14 * * 1-5'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r insolventa_sistem/insolventa/requirements.txt

      - name: Creeaza fisierul .env
        run: echo "${{ secrets.ENV_FILE }}" > insolventa_sistem/insolventa/variabile_mediu.env

      - name: Run monitor
        run: cd insolventa_sistem/insolventa && python main.py